### ISSUE TITLE
outer container and stock column

### ISSUE THREAD

**Issue by djnolan** [frontlinepbs/fl-base-blueprint#13]
Consider the different options for the outer container and the stock column mixin. The main issue is that there are different needs depending on whether it's an embedded vs standalone interactive. We might just need two different mixins and two different outer containers.

**Comment by eyeseast** [comment]
This might be the point at which we branch into two blueprints that build upon this one. I don't want to get too crazy with these, but it seems reasonable to have a blueprint for embedded graphics and a separate one for longform stories. Both could fork this very minimal codebase and add on as needed.
